version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    groups:
      go-smtp:
        patterns:
          - "^github.com/emersion/.*"
      k8s:
        patterns:
          - "^k8s.io/*"
          - "^sigs.k8s.io/*"
      ginkgo:
        patterns:
          - "^github.com/onsi/*"
      other:
        patterns:
          - "*"
        exclude-patterns:
          - "^github.com/emersion/.*"
          - "^k8s.io/*"
          - "^sigs.k8s.io/*"
          - "^github.com/onsi/*"
          - "^github.com/gruntwork-io/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
