linters:
  enable:
  - dupl
  - ginkgolinter
  - gocheckcompilerdirectives
  - gocognit
  - goconst
  - gocyclo
  - godot
  - gofmt
  - revive
  - typecheck
  - unparam
run:
  timeout: 5m
  build-tags:
  - test
  - e2e
