version: 2.1
executors:
  golang:
    docker:
      - image: quay.io/cybozu/golang:1.15-focal
  ubuntu:
    docker:
      - image: quay.io/cybozu/ubuntu:20.04

jobs:
  lint:
    executor: golang
    steps:
      - checkout
      - run:
          name: "Install python3"
          command: |
            apt-get update && apt-get install -y --no-install-recommends python3-pip
      - run: make lint
  test:
    executor: golang
    steps:
      - checkout
      - run: make test
  kindtest:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: make setup-kind
      - run: make kindtest
  verify:
    executor: golang
    steps:
      - checkout
      - run: make verify
  build:
    executor: golang
    working_directory: /work
    parameters:
      os:
        type: string
      arch:
        type: string
    steps:
      - checkout
      - run: make OS=<< parameters.os >> ARCH=<< parameters.arch >> build
      - persist_to_workspace:
          root: /tmp/ct-monitor
          paths:
            - artifacts/*
  create-tag:
    executor: golang
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ff:ca:da:a2:6d:ac:60:f3:0c:ec:59:fa:9c:1c:e6:9d"
      - checkout
      - run:
          command: |
            TAG=v$(cat VERSION)
            if git show-ref --tags | grep -q "refs/tags/${TAG}$"
            then
              echo "Already released version, skip"
              exit
            else
              git tag ${TAG}
              git push git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git ${TAG}
            fi
  release:
    executor: golang
    working_directory: /work
    steps:
      - attach_workspace:
          at: /tmp/ct-monitor
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} /tmp/ct-monitor/artifacts
  publish-docker:
    docker:
      - image: docker:stable
    working_directory: /work
    steps:
      - setup_remote_docker:
            docker_layer_caching: false
      - checkout
      - run: |
          BASENAME="quay.io/hsn723/ct-monitor"
          TAG=$(cat VERSION)
          BRANCH=$(echo $TAG | cut -d '.' -f 1,2)
          docker build -t ${BASENAME}:latest -t ${BASENAME}:${BRANCH} -t ${BASENAME}:${TAG} .
          docker login -u ${QUAY_USER} -p ${QUAY_TOKEN} quay.io
          docker push ${BASENAME}:${TAG}
          docker push ${BASENAME}:${BRANCH}
          docker push ${BASENAME}:latest

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test
      - verify
      - kindtest:
          requires:
            - lint
            - test
            - verify
      - build:
          requires:
            - kindtest
          matrix:
            parameters:
              os: [linux]
              arch: [amd64]
          filters:
            tags:
              only: /.*/
      - create-tag:
          requires:
            - build
          filters:
            branches:
              only: master
  create-release:
    jobs:
      - verify:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - build:
          requires:
            - verify
          matrix:
            parameters:
              os: [linux, darwin, windows]
              arch: [amd64]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-docker:
          requires:
            - verify
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
