[[domain]]
    name = "example.com"
    match_wildcards = true
    include_subdomains = false

[[domain]]
    name = "example.jp"
    match_wildcards = false
    include_subdomains = true

[smtp]
    from = "from@example.com"
    to = "to@example.com"
    server = "localhost"
    port = 25

[sendgrid]
    from = "from@example.com"
    to = "to@example.com"
    token = "hoge"
