certspotter_endpoint = "dummy.endpoint"
certspotter_token = "dummy"
[[domain]]
    name = "example.com"
    match_wildcards = true
    include_subdomains = false

[[domain]]
    name = "example.jp"
    match_wildcards = false
    include_subdomains = true

[alert_config]
    mailer_config = "sendgrid"

    [position_config]
        filename = "positions.toml"

[filter_config]
    filters = []

[smtp]
    from = "from@example.com"
    to = "to@example.com"
    server = "localhost"
    port = 25

[sendgrid]
    from = "from@example.com"
    to = "to@example.com"
    token = "hoge"

[mail_template]
    subject = "{{.Domain}}の証明書発行を検知しました"
    body = '''ct-monitorが{{.Domain}}の以下の証明書の発行を検知しました
{{range .Issuances}}
SHA256: {{.CertSHA256}}
{{end}}'''
