apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - cronjob.yaml
  - secrets.yaml
configMapGenerator:
  - name: ct-monitor-config
    files:
      - config.toml
