name: main
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
env:
  go-version: stable
  python-version: 3.x
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Lint
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  check-goreleaser-config:
    name: Check goreleaser.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check -f .goreleaser.yml
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Verify
        run: make verify
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Test
        run: make test
  kindtest:
    name: Kind test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: Setup kind
        run: make setup-kind
      - name: Run kindtest
        run: make kindtest
  dry-run:
    name: Dry-run release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: anchore/sbom-action/download-syft@v0.17.5
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: --snapshot --skip=sign,publish --clean
      - name: Test built containers
        run: make container-structure-test
  tag:
    name: Tag release
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [lint, verify, check-goreleaser-config, test, kindtest, dry-run]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Tag release
        run: |
          TAG="v$(cat VERSION)"
          git tag ${TAG}
          git push origin ${TAG} || true
