name: main
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master
permissions:
  contents: read
  pull-requests: write
jobs:
  verify:
    uses: hsn723/actions/.github/workflows/verify.yml@d7fb9a279f99f27dfd9aa008a97c6ec92ccfa330 # v1.0.34
    secrets: inherit
