name: main
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master
permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write
jobs:
  verify:
    uses: hsn723/actions/.github/workflows/verify.yml@47eeeef281da373b713e33dee8f0696a7c83e1c0 # v1.0.47
    secrets: inherit
