name: main
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master
permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write
jobs:
  verify:
    uses: hsn723/actions/.github/workflows/verify.yml@57366a300d9a0523621af11c2efcde2fdcf16aa3 # v1.0.41
    secrets: inherit
