name: release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/release.yml@a48f27c3e6fa5b0a099473cd4ff0aa71dafb6569 # v1.0.40
    secrets: inherit
