name: release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/release.yml@4281946d97b73d45fcb15360e18ecdc4aeeb3dae # v1.0.42
    secrets: inherit
